### ISSUE TITLE
Archive retrieve NULL result

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#11]
Is NULL allowed if nothing is to be returned?
The problem of the empty list is that the provider may not know the Element List concrete type so it may not be possible to return an empty list.

**Comment by SamCooper** [comment]
I think it must be possible, because if the object type may not have a payload specified for it. In this case you cannot return a list of NULL type so it should be NULL.

I will add this clarification.
