### ISSUE TITLE
Archive query on multiple object types

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#14]
_c) Each part of the object type may contain the wildcard value of '0'._

Does it make sense to define an ArchiveQuery and a QueryFilter for multiple object types that may not have the same body type?

What should happen if the QueryFilter cannot be applied (for example a CompositeFilter whose field does not exist in the object body)? Should the object be returned or ignored or should an error be raised?

**Comment by SamCooper** [comment]
It may make sense for some situations. I have added a clarification to the composite filter of what to do if the requested field not exists (specifically, fail the match).
