### ISSUE TITLE
Archive QueryFilter not applicable

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#15]
What should happen if a QueryFilter cannot be applied? Should the selected objects be returned or ignored or should an error be raised?

**Comment by SamCooper** [comment]
Could you give an example when it could not be applied?

**Comment by DavidFeliot** [comment]
For example, if the field name does not reference a field of the object payload.

More generally, the filter is correct (no mistake, it is correctly formed) but it cannot be applied because it is not related to the object (discrepancy).

**Comment by SamCooper** [comment]
Then the object would fail to match and therefore be ignored. I think I have text in there now to cover this.
