### ISSUE TITLE
CompositeFilter NULL field value

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#16]
In a CompositeFilter, is the value NULL allowed when the operator is either CONTAINS, or ICONTAINS, or GREATER, or GREATER_OR_EQUAL, or LESS, or LESS_OR_EQUAL?

If allowed, what should be the result of the operator in this case?

If not allowed, should an error be raised or should the filter be ignored?

**Comment by SamCooper** [comment]
An error should be raised, I have expanded the text to cover this.
