### ISSUE TITLE
Activity Service - Source object for MAL operations

### ISSUE THREAD

**Issue by ivandankiewicz** [SamCooper/COM_SPEC_RIDS#19]
Standard includes (section 3.4.2 d)  text:
All events for the interaction shall use the OperationActivity as their source object.

This implies  the OperationActivity shall be available to the provider and relays which is not the case. 
I understand the information that should be in the OperationActivity  is available so the information can be populated indirectly but the text should be clarified.

**Comment by SamCooper** [comment]
Extra text has been added.
