### ISSUE TITLE
Archive query results

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#2]
If a query produces two different object types, they cannot be returned in the same update/response message unless the payload types are the same.

Below are two examples using the Activity service. The first one works but not the second one.

1) Result of the archive query:
List<ObjectType> = {Release, Reception}
List<Element> = {activityTransfer1, activityTransfer2}

2) Result of the archive query:
List<ObjectType> = {Release, Execution}
List<Element> = {activityTransfer1, **activityExecution1**} **<-- Not the same type**

Could we restrain a query update (or response) to have a single ObjectType instead of a List<ObjectType>?

**Comment by SamCooper** [comment]
Change made in the specification.
