### ISSUE TITLE
Definition of EnityKey for MonitorEvent

### ISSUE THREAD

**Issue by ivandankiewicz** [SamCooper/COM_SPEC_RIDS#20]
In section 3.2.4.2 the description of Entitykey.secondSubkey is open to interpretation. The mapping would be unclear without the example.  
Proposed alternative:
The field is populated as shown below (in hex) 
0xAAAASSSSVVXXXXXX
Where:
AAAA = Area (16 bits)
SSSS = Service (16 bits)
VV = Version (8 bits)
XXXXXX = Unused (24 bits)

**Comment by SamCooper** [comment]
Updated.
