### ISSUE TITLE
Use of MAL transaction identifier in activity service 

### ISSUE THREAD

**Issue by ivandankiewicz** [SamCooper/COM_SPEC_RIDS#21]
Section 3.4.2 states that the OperationActivity object shall use the transaction identifier of the MAL operation for its object instance identifier.
However the MAL specification states the transaction identifier is optional for the Send operation.
A statement should be added specifying that if a MAL operation is using the activity service the transaction identifier must be populated.

**Comment by SamCooper** [comment]
Added extra requirement.
