### ISSUE TITLE
Archive query: sorting done for a given object type and domain

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#24]
Archive query:
_u) If multiple ObjectTypes or domains have been matched then multiple Update message shall be returned._

Could it be stated that the sorting is only done for a given object type and domain?

**Comment by SamCooper** [comment]
So that each message contents is sorted but not across messages?

**Comment by DavidFeliot** [comment]
No, that is not my point: an archive provider should be allowed to sort across several update messages. That is the purpose of the Progress interaction.

However, as the domain is unique for an update message, there are two solutions regarding the way the objects are sorted:
- they are sorted across the domains: this solution requires to flush an update each time the domain changes
- they are sorted for a given domain

Which solution should be specified?

**Comment by SamCooper** [comment]
I'll add in the restriction that each domain/object type pair is sorted internally, and not across domain/object type pairs.
