### ISSUE TITLE
Archive store: return empty list or NULL?

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#25]
_a) The first part of the request indicates whether the operation should return the object instance identifiers used, if TRUE it shall return them, otherwise not._

Should an empty list or NULL be returned?

**Comment by SamCooper** [comment]
Returns null, XML updated.

**Comment by DavidFeliot** [comment]
_j) The response shall contain the set of new object instance identifiers if the request supplied an initial TRUE Boolean value, otherwise it returns an empty list._

Actually the response was already given in statement j). Now there is a conflict between a) and j).

**Comment by SamCooper** [comment]
Fixed.
