### ISSUE TITLE
ArchiveQuery: field 'source'

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#26]
_The fields of the ObjectId may contain the wildcard values._

But the ObjectId fields cannot be NULL: 'Nullable' = False.

Moreover would the wildcard values be allowed in ObjectType and ObjectKey?

**Comment by SamCooper** [comment]
I've updated the comments on the fields to clarify. basically '0' is the numeric wildcard value and this is not allowed for actual instance id (for example).
