### ISSUE TITLE
Archive query: non-attribute field

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#28]
_If the field points to a non-attribute field then no sorting shall be applied._

The field can be an Enumeration (not an Attribute).

**Comment by DavidFeliot** [comment]
If Enumeration is not allowed for sorting then it should be removed from the following sentence in ArchiveQuery (sortFieldName):

_If the object body is not a composite but an Attribute or Enumeration then to sort on the values an empty string of "" should be used._

**Comment by SamCooper** [comment]
I've changed it so that enumerations can be sorted. I've also added in that they should be sorted on their ordinal rather than text.

**Comment by DavidFeliot** [comment]
They should be sorted on their ordinal rather than text **and their numerical value** (even if the ordinal and numerical values should be ordered in the same way).

**Comment by SamCooper** [comment]
updated.
