### ISSUE TITLE
Archive query: sorting error

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#29]
How should a sorting error be handled?

For example, if the field to sort across is NULL or not accessible (NULL parent composite) for some object instances, how should the query handle that error?

Should no sorting at all be applied?
Or should the object instances that cannot be sorted be inserted at the end (or at the beginning)?
Or should an error be returned?

**Comment by SamCooper** [comment]
I've added in that they should be added to the end.
