### ISSUE TITLE
CompositeFilter operators for non numeric comparable attributes

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#30]
Should the operators GREATER, GREATER_OR_EQUAL, LESS, or LESS_OR_EQUAL be defined for non numeric comparable attributes like Boolean and String?

Is Blob comparable?

**Comment by SamCooper** [comment]
I think the only one that isn't comparable is Blob, you can use those operators on all the other attribute types.

I'll add in something that excludes Blob from sorting.
