### ISSUE TITLE
Archive query: returned ArchiveDetails

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#32]
_w) The second returned list shall contain the matched object instance identifiers and the object details of the matched objects._

This statement emphasizes the 'Nullable' information (set to 'No') already given by ArchiveDetails. It cannot be tested as such.

However, the 'Nullable' fields from ArchiveDetails can be tested in the 'store' operation. And there is no statement about that like for example: the timestamp of an ArchiveDetails may be NULL.

**Comment by SamCooper** [comment]
What's the question?

**Comment by DavidFeliot** [comment]
Is this statement required?

Does it imply that the timestamp of the matched objects may not be returned (even if stored)?

**Comment by SamCooper** [comment]
I'll change it to:

The second returned list shall contain the archive details stored for the matched objects.
