### ISSUE TITLE
Archive store: no wildcard values

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#33]
_h) No wildcard values shall be accepted (except in the object instance identifier of the archive details), an INVALID error is returned in this case."_

Could this statement be made clearer? Could it be more explicit by listing the fields whose wildcard is forbidden?

**Comment by SamCooper** [comment]
I've changed it to:

No wildcard values shall be accepted in the object type, domain identifier list, or the archive details except for the object instance identifier, an INVALID error is returned if a wildcard is detected.

**Comment by DavidFeliot** [comment]
What are the allowed wildcard values in an archive details? Is it already specified somewhere?

**Comment by SamCooper** [comment]
Not explicitly.

**Comment by DavidFeliot** [comment]
It should be specified otherwise it is ambiguous (in the same way as in ArchiveQuery).

Nullable does not always mean wildcard. For example, the ObjectDetails 'related' can be NULL. But the wildcard would be '0'. It should be specified.
Same for 'source'. Would NULL be a wildcard (every ObjectId)? I guess not. The wildcards should be assigned to the fields of ObjectType and ObjectKey.

**Comment by SamCooper** [comment]
Should be better now. 

BTW, can you reopen these closed issues if you have extra comments on them as I don't always see them.
