### ISSUE TITLE
Archive query: return empty lists or NULL or nothing?

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#34]
If there is no result, should empty lists be returned or NULL or nothing (no update, but a final response with every parameter set to NULL)?

For example, a query for several object types (1,2) and domains (1,2) returning no result:
1) Empty lists:
update1: objectType1, domain1, [], []
update2: objectType1, domain2, [], []
response: objectType2, domain1, [], []

2) NULL:
update1: objectType1, domain1, NULL, NULL
update2: objectType1, domain2, NULL, NULL
response: objectType2, domain1, NULL, NULL

3) No Update:
response: NULL, NULL, NULL, NULL

**Comment by SamCooper** [comment]
Number 3, I've added in a rule for this.
