### ISSUE TITLE
Archive query: sort field name

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#35]
_n) If the sortFieldName of the ArchiveQuery does not reference a known field then an INVALID error shall be returned._

Instead of "known", could it be said "declared" or "defined"?

**Comment by DavidFeliot** [comment]
_aa)    When the field being sorted on contains a NULL value, or does not exist in the matched object, these entries shall be added to the end of the returned list in the order that they are matched._

Could it be explained what "exist" means? Is it limited to the case where a composite field is NULL?

**Comment by SamCooper** [comment]
I've expanded the rule, I think it is going to be limited to a containing composite being NULL and therefore the field being reference not 'existing'.
