### ISSUE TITLE
Archive query: sorting applied across updates

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#37]
_z) Each Update message shall be sorted separately from other Update messages, there is no requirement for sorting to be applied across updates._

Two questions about the above statement:

1) Does this statement enables an archive provider not to sort the results, by returning one update per object?

2) Is it the restriction that each domain/object type pair is sorted internally, and not across domain/object type pairs?

**Comment by SamCooper** [comment]
1) Yes, I guess it does, should I clarify this restriction?

2) Yes.

**Comment by DavidFeliot** [comment]
1) But it is not mandatory to loosen the ordering requirement that much. Is it really on purpose?

The restriction 2) can be ensured without the 1).

**Comment by SamCooper** [comment]
Could you suggest better wording?

**Comment by DavidFeliot** [comment]
Your wording in https://github.com/SamCooper/COM_SPEC_RIDS/issues/24 was perfect:

_I'll add in the restriction that each domain/object type pair is sorted internally, and not across domain/object type pairs._

**Comment by SamCooper** [comment]
Ok, updated.
