### ISSUE TITLE
Type restrictions and Attribute polymorphism

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#39]
Do the type restrictions refer to the declared type or the actual type at runtime?

Examples of type restrictions:
- ExpressionOperator: _String types only_
- ArchiveQuery: _If the field points to a composite, list, or Blob then no sorting shall be applied._

If they refer to the actual type, then is it allowed to filter or sort on a field typed Attribute (with polymorphism)? Does it make sense?

**Comment by SamCooper** [comment]
I think we have to go with the simplest option, you'll have to tell me which that is, as this is not meant to be a complete SQL equivalent but a simple query ability that should work in most cases.

**Comment by DavidFeliot** [comment]
May be the distinction declared/actual could remain implicit in the COM specification. It is more a matter of implementation. A type restriction can be checked before accessing the data if the declared type is not abstract.

However may be a statement could be added about the fact that a field can be declared as an abstract Attribute. What do you think? Would such a field be allowed? And could a COM object body be typed Attribute also (despite the restriction that a body should not be abstract)?

**Comment by SamCooper** [comment]
I think we made the distinction about attribute not being abstract in the MAL specification so I think we have to follow that here.

**Comment by DavidFeliot** [comment]
Not exactly. MAL says:
"The exception to this is the containment of the **abstract Attribute type**. It is permitted to
create composites that have fields defined as Attribute. This is because the set of possible
Attribute types is fixed."

So I agree but it should not be implicit. COM should state that an object body can be an abstract Attribute.

**Comment by SamCooper** [comment]
I'll add this in.

**Comment by DavidFeliot** [comment]
There is no concrete List<Attribute> type. Therefore, if an object body is typed Attribute, then it cannot be stored/retrieved/queried/updated using the Archive service.

So it seems that the type Attribute should be forbidden for an object body.

**Comment by SamCooper** [comment]
Sounds correct, I'll add that in too.

**Comment by SamCooper** [comment]
Done.
