### ISSUE TITLE
Archive store: NULL and empty object body

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#41]
When storing an object with an empty body, should the value NULL be used?

If so, then should the archive provider make a difference between objects with a NULL value and objects with an empty body?
For example, a query with a filter "EQUAL NULL" could return both without making any difference.

**Comment by DavidFeliot** [comment]
In order to make a difference between NULL and empty body, the object value list (List<MAL::Element>) could be NULL if the object body is empty, as the store is done for a given object type.

**Comment by SamCooper** [comment]
I don't think you can create an object with an empty body can you? It would always become NULL when using one of the standard operations there fore they are the same thing.

**Comment by DavidFeliot** [comment]
The COM event objects (ObjectStored, ObjectUpdated, ObjectDeleted) do not have any body: Object Payload Type is "not used". Is this an empty body COM object?

**Comment by SamCooper** [comment]
It is an empty body object but the monitorEvent PUBSUB operation takes a body part which would be NULL in this case. This is what I mean by the fact that although conceptually it doesn't have a body, in reality it has NULL for its body value, but its declared body type is not defined.

**Comment by DavidFeliot** [comment]
It could be a NULL list in the Pub/Sub Publish. It is the same problem actually.

A statement could be added to COM about this. Moreover, a NULL list is more efficient than a list containing NULLs.

And you cannot even create an instance of the list because there is no body type. So that is the only solution. Am I wrong?

**Comment by SamCooper** [comment]
Ok, I'll clarify about the rules for COM object bodies and how to deal with NULL bodies.

**Comment by DavidFeliot** [comment]
Yes, and how to deal with **empty** bodies.

**Comment by DavidFeliot** [comment]
The following statements are not clear:
_i) There shall be an entry in each returned list for each matched object unless the body of the object type is specified as NULL._
_l) If the body of the object is define as NULL then the second list shall be replaced with a NULL value._

**Comment by SamCooper** [comment]
Should be clarified.
