### ISSUE TITLE
Archive store: object body type checking

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#43]
Should the operation 'store' check that the object body type is compliant with the object type?

Should the archive provider statically know what object body type is expected for a given object type and raise an INVALID error if the object type is not correct?

**Comment by SamCooper** [comment]
No, otherwise things start getting complicated. I mean they could but that would not be standard.

**Comment by DavidFeliot** [comment]
So should the archive accept to store several different body types for the same object type?

That would be an error, potentially preventing from returning the object values after a query or a retrieve.

At least, an INVALID error should be raised in this case, even if the object type defined in the MO XML is not checked.

**Comment by SamCooper** [comment]
I've added that as a should rule.

**Comment by DavidFeliot** [comment]
Why "should"? Is it because it would be too restricted to constrain the archive to check the object body types?

**Comment by SamCooper** [comment]
Because there may be situations where it is not possible to check it at runtime (performance/ability) and therefore you can get around this in other ways such as just making sure the situation never occurs.

**Comment by DavidFeliot** [comment]
Yes, like an archive implementation storing the objects as arbitrary byte arrays, without decoding the content.
