### ISSUE TITLE
COM object: body type restriction

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#44]
As already discussed, the body type should be restricted to concrete types only.

Moreover a body type cannot be a list (which is not a real data type). Could you confirm?

**Comment by SamCooper** [comment]
Is there need for a rule somewhere?

**Comment by DavidFeliot** [comment]
Yes, I though there was one somewhere. But it seems that there is none.

By the way, the type Attribute (abstract) should be mentioned (allowed or forbidden).

**Comment by SamCooper** [comment]
This needs to be clarified in section 3 somewhere but I'm not sure where, I'll add it though.

**Comment by SamCooper** [comment]
Done.
