### ISSUE TITLE
Archive update: updated object details

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#46]
_d) The object instance identifiers and object details contained in the ArchiveDetails shall be used to match objects._

This statement is not clear because the object details is not part of the object identifier (object type, domain and instance id).

Does it mean that the object details should not be updated?
If so, what should happen if the object details do not match an archived object (because they have been updated)? Should an error be returned? Or should the update be ignored?

**Comment by SamCooper** [comment]
I have changed it to

"The object instance identifier contained in the ArchiveDetails, combined with the object type and domain from the request, shall be used to match objects."

I have also added in a rule to fail with UNKNOWN if any object does not already exist.
