### ISSUE TITLE
Archive update: updated ArchiveDetails 

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#47]
_e) The remainder of the ArchiveDetails shall be used to update the matched objects._

Does it mean that the timestamp could be updated?

Would a NULL timestamp be a valid value as an update?

**Comment by SamCooper** [comment]
I guess so on both part as I don't think the archive uses those fields? What do you think?

**Comment by DavidFeliot** [comment]
What do you mean by using those fields? Why are the ObjectDetails used and not the timestamp/network/provider? What is the difference? Could the COM explain this (even as a note)?

**Comment by SamCooper** [comment]
A COM object is identified by the type, domain and instance identifier. The timestamp/network/provider fields do not contribute to the identification of an object instance. So it is possible to logically modify the timestamp in the archive because it should not be a key field.

**Comment by DavidFeliot** [comment]
What about the ObjectDetails? Do they contribute to the identification of an object instance (in the context of the update operation)?

**Comment by SamCooper** [comment]
Nope, the rules currently for that operation are:

"The object instance identifier contained in the ArchiveDetails, combined with the object type and domain from the request, shall be used to match objects."

**Comment by DavidFeliot** [comment]
Ok.

Is the following statement still correct?

_e) The remainder of the ArchiveDetails shall be used to update the matched objects._

In other terms, should the ObjectDetails also be updated?

**Comment by SamCooper** [comment]
Yes, everything else you provide will be used to update the object in the archive.

**Comment by DavidFeliot** [comment]
Ok.
