### ISSUE TITLE
Archive delete: returned list of instance identifiers

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#49]
_h) The response shall contain the set of object instance identifiers of the deleted objects._

As the object type may contain some wildcards, several objects having the same identifier but not the same object type can be deleted. So the returned set of object instance identifiers may not be enough to uniquely identify the instances that have been deleted.
Is that correct and expected?

Would it be possible not to allow the wildcard in the object type?

**Comment by SamCooper** [comment]
No wildcards would make sense, I'll change it to being that.
