### ISSUE TITLE
Archive query: NULL list or list of NULLs?

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#52]
_a) The first part of the request shall contain a Boolean that if set to TRUE requests that the body of the objects is returned otherwise only the ObjectType and ArchiveDetails shall be returned and the body of the objects shall be a NULL._

Should the returned body list be NULL or should it be a list full of NULLs?

**Comment by SamCooper** [comment]
Changed to:

"The first part of the request shall contain a Boolean that if set to TRUE requests that the body of the objects is returned otherwise only the ObjectType and ArchiveDetails shall be returned and the returned list of the bodies of the objects shall be replaced with a NULL."
