### ISSUE TITLE
Activity Tracking: Progress stage count

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#53]
Is there a statement about the way progress stages should be counted?

It seems that the initial Progress and the final Response should be excluded. Is it correct?

**Comment by SamCooper** [comment]
What makes you say that?

**Comment by DavidFeliot** [comment]
The current Progress test expecting two.

Anyway, is there a rule?

**Comment by SamCooper** [comment]
Yes, if we are talking about the stageCount field then it is the total number of PROGRESS_UPDATE messages plus 1 for the PROGRESS_RESPONSE message. 

The first PROGRESS_UPDATE message will have an execution stage of '1', the second '2', etc

**Comment by DavidFeliot** [comment]
What about the Progress Ack? Is it ignored?

**Comment by SamCooper** [comment]
No, sorry, that's included so add one to those numbers.

**Comment by SamCooper** [comment]
Done.
