### ISSUE TITLE
Activity Tracking: execution stage first value

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#54]
The 'executionStage' holds the interaction stage for a MAL operation.

Should its first value be '1' or '2' (SUBMIT Ack, REQUEST Response, INVOKE Ack, Progress Ack)?

**Comment by SamCooper** [comment]
It does not hold the interaction stage but the execution stage, this is different to the stage in the interaction pattern.

So, for the stages given above it would be '1'.

This needs to be clarified in the document.

**Comment by DavidFeliot** [comment]
It needs to be clarified because the current text is:
"The execution stage of the operation. Holds the **interaction stage** for a MAL operation, service specific for when being used by another service (such as automation)."

**Comment by SamCooper** [comment]
Ok, I will clarify.

**Comment by SamCooper** [comment]
Done.
