### ISSUE TITLE
Activity Tracking: next destination URI

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#55]
ActivityTransfer: nextDestination
_This contains the URI of the next destination, either another relay or the provider. It is protocol specific how this value is derived._

If we accept the fact that MAL interactions are end-to-end, then the relays should not be seen as service providers. So what should the URI field 'nextDestination' reference when the next destination is a relay?

**Comment by SamCooper** [comment]
It should provide some means to uniquely identify the next relay. How this is done is outside the scope of the specification.

But you must be able to identify the next 'entity' that will be passing the original message.

**Comment by DavidFeliot** [comment]
Should the 'source URI' (UpdateHeader) of the updates published by a relay follow the same rule?

**Comment by SamCooper** [comment]
Yes, the source of the events is the relay.

**Comment by SamCooper** [comment]
Added rule to Activity event support.
