### ISSUE TITLE
Event: unique event id

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#56]
_c) The MAL::EntityKey.thirdSubKey shall contain the event object instance identifier._

Should an Event publisher ensure that the event instance id is unique for a given object type and domain?

For example, should ActivityTracking relays ensure that Reception/Forward event ids are unique?

**Comment by SamCooper** [comment]
Yes, for a given object type and domain.

**Comment by SamCooper** [comment]
Nothing to change.
