### ISSUE TITLE
ActivityTracking: OperationActivity unique instance id

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#58]
_c) The OperationActivity object shall use the transaction identifier of the MAL operation for its object instance identifier._

According to MAL, the transaction id is unique in the following context:
_The originating MAL shall ensure that the combination of the following Message
Header fields form a unique index: pattern type, transaction identifier, the source address, the session, the domain, the network, the service area, the service, and operation._

The COM requires that _"every COM object is uniquely identified by the set (domain, area, service, area version, object type, object instance identifier)"_.

What should be the domain of an OperationActivity in order to make the instance id (mapped to the transaction id) unique?

**Comment by SamCooper** [comment]
It has to be something that the relays will be able to derive from the message they are passing so it is the domain in the message.

**Comment by SamCooper** [comment]
Done.
