### ISSUE TITLE
Query CompositeFilter issue

### ISSUE THREAD

**Issue by ivandankiewicz** [SamCooper/COM_SPEC_RIDS#61]
The specification states that the fieldValue is of type MAL::Attribute but does not indicate which subtypes are valid. If the intention is that the type shall be the same as the type of the returned value, then the specification should state this, and also cover how queries resulting in multiple values with multiple types shall be handled. (One approach would be that if the type of the fieldValue does not correspond to the type of a value, then the value has not matched the filter).

**Comment by SamCooper** [comment]
I think the rule should be that the types shall match. the slight twist to that is when the specified type is an Attribute but in that case the dynamic type should match.

**Comment by SamCooper** [comment]
Issue 39 is going in the direction that you cannot filter on an abstract field it must be a concrete type.

**Comment by SamCooper** [comment]
Done.
