### ISSUE TITLE
Query Sort issues

### ISSUE THREAD

**Issue by ivandankiewicz** [SamCooper/COM_SPEC_RIDS#62]
A query can result in a number of values which have different types (where wildcards are used in the query). The specification does not specify how sorting should be performed in this case.  Note the specification states that if the body is an Attribute then the sortFiedName should be an empty string this means that it is possible in this case that the sort is performed on values of different types.

**Comment by SamCooper** [comment]
Does Issue 37 cover this?:

https://github.com/SamCooper/COM_SPEC_RIDS/issues/37

**Comment by SamCooper** [comment]
Added in that sort field must point to a concrete field. There is already a rule in query that states that each domain/object type is sorted separately from each other therefore you should never have different types matching the sort field.
