### ISSUE TITLE
CompositeFilter 'fieldName'

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#8]
If the field is a Composite the fields of that Composite can be referenced by their name, separated from the **parent composite name** by a '.' character.'

Is it the parent composite **field** name?

Should fields typed 'List' be excluded from that rule?

**Comment by SamCooper** [comment]
Field referencing now includes an example.

What do you think about accessing list elements?

**Comment by DavidFeliot** [comment]
A List is usually a dynamic structure.

If there is need to filter on an element of a list then it shows that the list is actually static, otherwise the filter would not work.

I think that COM objects should not contain any static list. They should split such a static list in several fields.

However, there is the AggregationValue object that owns a static list for ParameterValue elements. There are probably some other objects like this one in MC.

So there is probably a need to have a filter for static lists. What do you think?

**Comment by SamCooper** [comment]
I think that we should rule out lists, if you need that kind of ability then you should be using some private extension or other means of querying the DB. Otherwise it will be just adding complexity that will probably never be used.

I'll add statements saying that lists are not supported.
