### ISSUE TITLE
Event Service - Nullable object body

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/COM_SPEC_RIDS#89]
When one publishes an Event, it is possible to send a null on the object body of the Event. This happens on the M&C and Common books.
However, this is not allowed by the lower layers as publishing must have all the fields with a list of the same size.
I believe that I have discussed this issue with Sam and the solution is to send a dummy list filled-in with dummy objects with the same size of the header and object details. (I thing the suggestion back then was UInteger())

Please add the requirement on the COM book, same section as the monitorEvent operation (3.3.4) to prevent this from happening again in the future.

**Comment by SamCooper** [comment]
This is actually an issue with the MAL and Java API, see:
https://github.com/SamCooper/JAVA_SPEC_RIDS/issues/23
